# File: .github/workflows/build-apk.yml
name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix Corrupted Gradle Wrapper JAR
        run: |
          curl -sSL -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar

      - name: Create Dummy local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build APK (Target App Module)
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: List Generated APKs
        run: |
          find . -name "*.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gallery-Debug-APK
          path: '**/*.apk'
